//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khatabahi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feature
    {
        public int FeatureID { get; set; }
        public string FeatureName { get; set; }
        public string FeatureDetail { get; set; }
        public string img { get; set; }
    }
}
