//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khatabahi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int FeedbackID { get; set; }
        public string CustName { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}
