//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khatabahi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductSubHead { get; set; }
        public string ProductDetail { get; set; }
        public string img { get; set; }
        public int cost { get; set; }
        public string ProductType { get; set; }
        public string ProductPdf { get; set; }
        public int Validity { get; set; }
    }
}
